### ISSUE TITLE
Blank exports

### ISSUE THREAD

**Issue by flinch44** [colinrsmall/ehm_roster_tools#5]
Scrapes are bringing up blank .csvs

**Comment by colinrsmall** [comment]
Thanks for the report. Can you give me more information? What leagues you're scraping and what settings you're using?

**Comment by flinch44** [comment]
![scrape](https://user-images.githubusercontent.com/66501039/120379166-9991e080-c2dc-11eb-8ea5-5a8c0cae43a5.PNG)
![missing dob](https://user-images.githubusercontent.com/66501039/120379169-9a2a7700-c2dc-11eb-9440-ce9b97efda43.PNG)

**Comment by colinrsmall** [comment]
This was just fixed. Can you refresh and try again?

**Comment by flinch44** [comment]
![missing dob](https://user-images.githubusercontent.com/66501039/120380799-dc54b800-c2de-11eb-9c4e-79f4c545d3c7.PNG)
![closer](https://user-images.githubusercontent.com/66501039/120380802-dced4e80-c2de-11eb-996c-f41ce9f48fc6.PNG)


Much closer, still not pulling DOB but it wasn't grabbing any of the other information before

**Comment by colinrsmall** [comment]
Should be fixed
